### PR TITLE
Use flex to position header navigation elements

### LINKED ISSUE #92: Use flexbox to position header navigation elements
See https://github.com/exercism/v3-dashboard/pull/91#discussion_r452258275

### PR DESCRIPTION
**Pull request by angelikatyborska**
Closes #92

### CODE REVIEW

**Comment by angelikatyborska** [comment]
@SleeplessByte Looks exactly the same in my choice of 4 different testing browsers on a mac (that includes Edge 😎). What would you use instead of `space-between`? `flex-grow: 1` on the link with the logo?

**Comment by SleeplessByte** [comment]
Probably `margin-right: 'auto'` or `margin-left: 'auto'`.

- `space-between` stops works when you add more items to the header (because now they become "equally spaced")
- the "intent" of `mr-auto` / `ml-auto` is like `float right`: I want all the available space to the left/right to fill up with margin.

And yet another technique I've used sparingly: add an _extra_ element in the middle with a `flex: 1` and base size of 0, whereas the other things are not flex 🔢

**Comment by SleeplessByte** [comment]
Happy number 💯 .

@ErikSchierboom when you push it up, can you ping us here so we know it's deployed  🥇 ?

**Comment by ErikSchierboom** [comment]
@angelikatyborska Thanks a lot for doing this! I've just deployed this 🎉 
CC @SleeplessByte

**Pull request merged**
